version: '3'
services:
    go_finance:
        image: postgres:14-alpine
        container_name: postgres-db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=go_finance
            - DATABASE_HOST=localhost
        ports:
            - '5432:5432'
        volumes:
            - database_postgres:/var/lib/postgresql/data

volumes:
    database_postgres:
